  name: "pyaml"
  type: "parser"
  language: "C"
  architecture: "x86_64"
  system: "linux"
  build:
    version: "1.0.2"
    release: "alpha"
    license: "MIT"
  author:
    name: "AntiSecTech"
    contact: "contact.antisec@pm.me"
  config:
    sheme: "dark"
